// Comprehensive Mock Data for all portals

export const mockStudentProfile = {
  srn: 'PES2202020001',
  name: 'Arjun Patel',
  branch: 'Computer Science & Engineering',
  semester: 6,
  section: 'A',
  email: 'arjun.patel@pes.edu',
  cgpa: 8.45,
  phone: '+91 98765 43210',
  profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
  dob: '2004-03-15',
  registrationStatus: 'Registered',
  selectedElectives: {
    elective3: {
      code: 'CS311',
      name: 'Machine Learning',
      credits: 4,
      department: 'CSE',
    },
    elective4: {
      code: 'CS312',
      name: 'Cloud Computing',
      credits: 4,
      department: 'CSE',
    },
  },
};

export const mockFacultyProfile = {
  id: 'FAC001',
  name: 'Dr. Priya Sharma',
  department: 'Computer Science & Engineering',
  designation: 'Associate Professor',
  email: 'priya.sharma@pes.edu',
  phone: '+91 98765 43211',
  office: 'Building A, Room 304',
  profileImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
  researchInterests: ['Machine Learning', 'Deep Learning', 'NLP'],
  totalElectives: 3,
  totalStudents: 65,
  experience: '12 years',
};

export const mockAdminProfile = {
  id: 'ADMIN001',
  name: 'Dr. Rajesh Kumar',
  email: 'admin@pes.edu',
  department: 'Academic Affairs',
  profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop',
};

export const mockElectives = [
  {
    id: 1,
    code: 'CS311',
    name: 'Machine Learning',
    credits: 4,
    department: 'CSE',
    prerequisites: ['CS201', 'CS202'],
    description: 'Advanced techniques in machine learning including supervised and unsupervised learning',
    availableSeats: 45,
    enrolledStudents: 55,
    technologies: ['Python', 'TensorFlow', 'Scikit-learn'],
    faculty: ['Dr. Priya Sharma', 'Prof. Amit Singh'],
    semester: 6,
    status: 'Active',
  },
  {
    id: 2,
    code: 'CS312',
    name: 'Cloud Computing',
    credits: 4,
    department: 'CSE',
    prerequisites: ['CS203'],
    description: 'Infrastructure, platforms, and services in cloud computing',
    availableSeats: 40,
    enrolledStudents: 60,
    technologies: ['AWS', 'Azure', 'Docker', 'Kubernetes'],
    faculty: ['Prof. Rajesh Gupta', 'Dr. Neha Verma'],
    semester: 6,
    status: 'Active',
  },
  {
    id: 3,
    code: 'CS313',
    name: 'Cybersecurity',
    credits: 4,
    department: 'CSE',
    prerequisites: ['CS204'],
    description: 'Security principles, cryptography, and network security',
    availableSeats: 50,
    enrolledStudents: 50,
    technologies: ['Encryption', 'Firewalls', 'Penetration Testing'],
    faculty: ['Dr. Vikram Singh', 'Prof. Anjali Desai'],
    semester: 6,
    status: 'Active',
  },
  {
    id: 4,
    code: 'CS314',
    name: 'Data Science',
    credits: 4,
    department: 'CSE',
    prerequisites: ['CS201'],
    description: 'Data analysis, visualization, and predictive modeling',
    availableSeats: 35,
    enrolledStudents: 65,
    technologies: ['Python', 'Pandas', 'Matplotlib', 'SQL'],
    faculty: ['Dr. Priya Sharma', 'Prof. Rohit Kumar'],
    semester: 6,
    status: 'Active',
  },
  {
    id: 5,
    code: 'IT301',
    name: 'IoT and Embedded Systems',
    credits: 4,
    department: 'IT',
    prerequisites: ['CS202'],
    description: 'Internet of Things, sensors, and embedded systems design',
    availableSeats: 30,
    enrolledStudents: 70,
    technologies: ['Arduino', 'Python', 'MQTT', 'Raspberry Pi'],
    faculty: ['Prof. Suresh Kumar', 'Dr. Meera Patel'],
    semester: 6,
    status: 'Active',
  },
  {
    id: 6,
    code: 'ECE301',
    name: 'Signal Processing',
    credits: 4,
    department: 'ECE',
    prerequisites: ['MA201'],
    description: 'Digital signal processing and applications',
    availableSeats: 25,
    enrolledStudents: 75,
    technologies: ['MATLAB', 'DSP', 'Filtering'],
    faculty: ['Prof. Arjun Verma', 'Dr. Sonia Singh'],
    semester: 6,
    status: 'Active',
  },
];

export const mockFacultyMembers = [
  {
    id: 1,
    name: 'Dr. Priya Sharma',
    designation: 'Associate Professor',
    department: 'CSE',
    email: 'priya.sharma@pes.edu',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    experience: '12 years',
  },
  {
    id: 2,
    name: 'Prof. Amit Singh',
    designation: 'Assistant Professor',
    department: 'CSE',
    email: 'amit.singh@pes.edu',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    experience: '8 years',
  },
  {
    id: 3,
    name: 'Prof. Rajesh Gupta',
    designation: 'Professor',
    department: 'CSE',
    email: 'rajesh.gupta@pes.edu',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop',
    experience: '18 years',
  },
];

export const mockStudents = [
  {
    srn: 'PES2202020001',
    name: 'Arjun Patel',
    branch: 'CSE',
    semester: 6,
    cgpa: 8.45,
    registrationStatus: 'Registered',
    electives: ['CS311', 'CS312'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
  },
  {
    srn: 'PES2202020002',
    name: 'Shreya Desai',
    branch: 'CSE',
    semester: 6,
    cgpa: 8.92,
    registrationStatus: 'Registered',
    electives: ['CS313', 'CS314'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
  },
  {
    srn: 'PES2202020003',
    name: 'Rohan Kumar',
    branch: 'CSE',
    semester: 6,
    cgpa: 7.88,
    registrationStatus: 'Pending',
    electives: [],
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop',
  },
  {
    srn: 'PES2202020004',
    name: 'Neha Verma',
    branch: 'IT',
    semester: 6,
    cgpa: 8.65,
    registrationStatus: 'Registered',
    electives: ['CS311', 'IT301'],
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
  },
  {
    srn: 'PES2202020005',
    name: 'Vikram Singh',
    branch: 'CSE',
    semester: 6,
    cgpa: 8.12,
    registrationStatus: 'Registered',
    electives: ['CS314', 'CS313'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
  },
];

export const mockAllFaculty = [
  {
    id: 'FAC001',
    name: 'Dr. Priya Sharma',
    department: 'CSE',
    designation: 'Associate Professor',
    electives: ['CS311', 'CS314'],
    workload: 65,
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    email: 'priya.sharma@pes.edu',
    status: 'Active',
  },
  {
    id: 'FAC002',
    name: 'Prof. Rajesh Gupta',
    department: 'CSE',
    designation: 'Professor',
    electives: ['CS312'],
    workload: 45,
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop',
    email: 'rajesh.gupta@pes.edu',
    status: 'Active',
  },
  {
    id: 'FAC003',
    name: 'Dr. Vikram Singh',
    department: 'CSE',
    designation: 'Assistant Professor',
    electives: ['CS313'],
    workload: 55,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    email: 'vikram.singh@pes.edu',
    status: 'Active',
  },
];

export const mockNotifications = [
  {
    id: 1,
    title: 'Registration Window Open',
    message: 'Elective registration for Semester 6 is now open. Register your preferences now.',
    type: 'info',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    read: false,
  },
  {
    id: 2,
    title: 'Registration Deadline Reminder',
    message: 'Only 3 days remaining to complete your elective registration.',
    type: 'warning',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    read: false,
  },
  {
    id: 3,
    title: 'Registration Confirmed',
    message: 'Your elective preferences have been submitted successfully.',
    type: 'success',
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    read: true,
  },
];

export const mockAdminStats = {
  totalStudents: 450,
  registeredStudents: 380,
  pendingStudents: 70,
  totalFaculty: 35,
  totalElectives: 18,
  availableSeats: 280,
  registrationStatus: 'Open',
  registrationDeadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
};

export const mockChartData = {
  registrations: [
    { day: 'Mon', count: 45 },
    { day: 'Tue', count: 52 },
    { day: 'Wed', count: 68 },
    { day: 'Thu', count: 82 },
    { day: 'Fri', count: 95 },
    { day: 'Sat', count: 78 },
    { day: 'Sun', count: 65 },
  ],
  electivePopularity: [
    { name: 'CS311', students: 55 },
    { name: 'CS312', students: 60 },
    { name: 'CS313', students: 50 },
    { name: 'CS314', students: 65 },
    { name: 'IT301', students: 70 },
    { name: 'ECE301', students: 75 },
  ],
  branchWise: [
    { branch: 'CSE', registered: 120, pending: 20 },
    { branch: 'IT', registered: 95, pending: 15 },
    { branch: 'ECE', registered: 85, pending: 25 },
    { branch: 'MECH', registered: 80, pending: 10 },
  ],
};

export const mockDepartments = [
  { id: 1, name: 'Computer Science & Engineering', code: 'CSE', electives: 6 },
  { id: 2, name: 'Information Technology', code: 'IT', electives: 3 },
  { id: 3, name: 'Electronics & Communication', code: 'ECE', electives: 4 },
  { id: 4, name: 'Mechanical Engineering', code: 'MECH', electives: 3 },
];

export const mockFacultyElectives = [
  {
    code: 'CS311',
    name: 'Machine Learning',
    students: 55,
    status: 'Active',
    department: 'CSE',
  },
  {
    code: 'CS314',
    name: 'Data Science',
    students: 65,
    status: 'Active',
    department: 'CSE',
  },
];

export const mockStudentListForFaculty = [
  {
    srn: 'PES2202020001',
    name: 'Arjun Patel',
    cgpa: 8.45,
    branch: 'CSE',
    preference: 'Preference 1',
    status: 'Confirmed',
  },
  {
    srn: 'PES2202020004',
    name: 'Neha Verma',
    cgpa: 8.65,
    branch: 'IT',
    preference: 'Preference 2',
    status: 'Confirmed',
  },
  {
    srn: 'PES2202020005',
    name: 'Vikram Singh',
    cgpa: 8.12,
    branch: 'CSE',
    preference: 'Preference 3',
    status: 'Confirmed',
  },
];

export const mockAttendanceData = [
  { date: '2026-01-15', status: 'present' },
  { date: '2026-01-16', status: 'present' },
  { date: '2026-01-17', status: 'absent' },
  { date: '2026-01-18', status: 'present' },
  { date: '2026-01-19', status: 'present' },
];
